- project:
    queue: barbican
    templates:
      - tempest-plugin-jobs
      - check-requirements
    check:
      jobs:
        - barbican-tempest-plugin-simple-crypto
        - barbican-tempest-plugin-simple-crypto-secure-rbac
        - barbican-tempest-plugin-simple-crypto-2023-1
        - barbican-tempest-plugin-simple-crypto-zed
        - barbican-tempest-plugin-simple-crypto-yoga
        - barbican-tempest-plugin-simple-crypto-xena
        - barbican-tempest-plugin-simple-crypto-wallaby
        - barbican-tempest-plugin-simple-crypto-ipv6-only
        - barbican-tempest-plugin-simple-crypto-castellan-src
        - barbican-tempest-plugin-simple-crypto-cursive
    gate:
      jobs:
        - barbican-tempest-plugin-simple-crypto

- job:
    name: barbican-tempest-plugin-simple-crypto
    parent: devstack-tempest
    required-projects: &barbican-tempest-reqs
      - opendev.org/openstack/barbican
      - opendev.org/openstack/barbican-tempest-plugin
      - opendev.org/openstack/python-barbicanclient
    vars: &barbican-tempest-vars
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
      devstack_localrc:
        NOVA_BACKEND: LVM
        LVM_VOLUME_CLEAR: none
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            glance:
              verify_glance_signatures: True
            ephemeral_storage_encryption:
              key_size: 256
              cipher: aes-xts-plain64
              enabled: True
        test-config:
          $TEMPEST_CONFIG:
            auth:
              tempest_roles: creator
            image-feature-enabled:
              # this may be removed soon, as api_v1 is false since tempest>=20
              api_v1: False
            ephemeral_storage_encryption:
              enabled: True
            key_manager:
              min_microversion: '1.0'
              max_microversion: latest
      tox_envlist: all
      tempest_test_regex: barbican
      tempest_plugins:
        - barbican-tempest-plugin

- job:
    name: barbican-tempest-plugin-simple-crypto-2023-1
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.1
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            key_manager:
              min_microversion: '1.0'
              max_microversion: '1.1'

- job:
    name: barbican-tempest-plugin-simple-crypto-zed
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            key_manager:
              min_microversion: '1.0'
              max_microversion: '1.1'

- job:
    name: barbican-tempest-plugin-simple-crypto-yoga
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga
    vars: &microversion_v1_0
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            key_manager:
              min_microversion: '1.0'
              max_microversion: '1.0'

- job:
    name: barbican-tempest-plugin-simple-crypto-xena
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-wallaby
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: wallaby-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-victoria
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: stable/victoria
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: victoria-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ussuri
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: ussuri-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-train
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: train-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-secure-rbac
    parent: barbican-tempest-plugin-simple-crypto
    vars:
      devstack_local_conf:
        post-config:
          $BARBICAN_CONF:
            oslo_policy:
              enforce_new_defaults: True
              enforce_scope: True
            secretstore:
              enable_multiple_secret_stores: True
              stores_lookup_suffix: simple_crypto
            secretstore:simple_crypto:
              secret_store_plugin: store_crypto
              crypto_plugin: simple_crypto
              global_default: true
        test-config:
          $TEMPEST_CONFIG:
            barbican_rbac_scope_verification:
              enforce_scope: True
            barbican_tempest:
              enable_multiple_secret_stores: True

- job:
    name: barbican-tempest-plugin-simple-crypto-secure-rbac-yoga
    parent: barbican-tempest-plugin-simple-crypto-secure-rbac
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-secure-rbac-xena
    parent: barbican-tempest-plugin-simple-crypto-secure-rbac
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-secure-rbac-wallaby
    parent: barbican-tempest-plugin-simple-crypto-secure-rbac
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: wallaby-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only
    parent: devstack-tempest-ipv6
    required-projects: *barbican-tempest-reqs
    vars: *barbican-tempest-vars


- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-yoga
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-xena
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-wallaby
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: wallaby-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-victoria
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-focal
    override-checkout: stable/victoria
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: victoria-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-ussuri
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: ussuri-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-train
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects:
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: train-last
    vars: *microversion_v1_0

- job:
    name: barbican-tempest-plugin-simple-crypto-castellan-src
    parent: barbican-tempest-plugin-simple-crypto
    required-projects:
      - opendev.org/openstack/castellan

- job:
    name: barbican-tempest-plugin-simple-crypto-cursive
    parent: barbican-tempest-plugin-simple-crypto
    required-projects:
      - opendev.org/x/cursive
